import {
  lyrGraatone,
  lyrFarger,
  lyrBuffersone,
  lyrRandsone,
  lyrUtbygging,
  lyrLosmasser,
  lyrVann,
  lyrByggAdresse,
  lyrMatrikkel,
  lyrVannNett,
  lyrFremmedeArter,
  lyrTruedeArter,
  lyrFlomAkt,
  lyrMarinGrense,
  lyrKvikkleire,
  lyrGranada,
  lyrKulturminner,
  lyrGrunnForurensning,
  lyrVannmiljo,
} from "./layersDefinitions";

export const layers = {
  basemaps: {
    "Gråtone": lyrGraatone,
    "Farger": lyrFarger,
  },
  overlays: {
    "Buffersone avløp (100 m)": lyrBuffersone,
    "Randsone-områder": lyrRandsone,
    "Nye VA-traseer": lyrUtbygging,
    "Eiendom": lyrMatrikkel,
    "Bygninger": lyrByggAdresse,
    "Vannflater": lyrVann,
    "Økologisk tilstand (Vann-Nett)": lyrVannNett,
    "Løsmassekart": lyrLosmasser,
    "Flom (200 år) aktsomhet": lyrFlomAkt,
    "Marin Grense": lyrMarinGrense,
    "Kvikkleire": lyrKvikkleire,
    "Grunnvann (Granada)": lyrGranada,
    "Grunnforurensning": lyrGrunnForurensning,
    "Vannmiljø": lyrVannmiljo,
    "Fremmede arter": lyrFremmedeArter,
    "Truede arter": lyrTruedeArter,
    "Kulturminner": lyrKulturminner,
  },
};
